/:
    page       : homepage
    lang       : nl
    title      : Welkom
    intro      : Ontdek wat u uit <br />het web kunt halen.
    bg_image   : man-laptop
/diensten:
    page       : services
    lang       : nl
    title      : Diensten
    intro      : Web oplossingen <br />die het verschil maken.
    bg_image   : man-mac
/werk:
    page       : work
    lang       : nl
    title      : Werk
    intro      : Resultaten die <br />voor zich spreken.
    bg_image   : woman-shop
    scripts    :
        - //ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js
        - /fancybox/jquery.fancybox.pack.js?v=2.1.5
        - /js/work.js
/over-mij:
    page       : about
    lang       : nl
    title      : Over mij
    intro      : Passie voor vooruitgang, <br/> hart voor uw zaak.
    bg_image   : stairs-handshake
/contact:
    page       : contact
    lang       : nl
    title      : Contact
    intro      : Neem vandaag nog <br />de eerste stap.
    bg_image   : woman-phone
    scripts    :
        - //ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js
        - /js/contactform.js
/contact/process:
    action     : ContactForm.processForm
    page       : contact
    lang       : nl
# --- English ------------------------------
/en/:
    page       : homepage
    lang       : en
    title      : Welcome
    intro      : Discover how you can <br />get more out the web.
    bg_image   : man-laptop
/en/services:
    page       : services
    lang       : en
    title      : Services
    intro      : Web solutions that <br />make the difference.
    bg_image   : man-mac
/en/work:
    page       : work
    lang       : en
    title      : Work
    intro      : Results that speak <br />for themselves.
    bg_image   : woman-shop
    scripts    :
        - //ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js
        - /fancybox/jquery.fancybox.pack.js?v=2.1.5
        - /js/work.js
/en/about-me:
    page       : about
    lang       : en
    title      : About Me
    intro      : Passion for progress, <br />heart for your business.
    bg_image   : stairs-handshake
/en/contact:
    page       : contact
    lang       : en
    title      : Contact
    intro      : Discover the possibilities and start today.
    bg_image   : woman-phone
    scripts    :
        - //ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js
        - /js/contactform.js
/en/contact/process:
    action     : ContactForm.processForm
    page       : contact
    lang       : en