# Database
database:
    username: root
    password: Di19Mp78!
    name: compare
    default_object_namespace: \Application\Domain\Entity

# Logging
log:
    path: application/log

# Templating
templating:
    default: page.php