# Modules
#
# You can have modules (for example, site + admin). You can also comment it out or remove it.
# In this case, the standard /application/config/actions.yml file is used.
# If you have modules, /application/config/actions_<module>.yml is read.

# root_path defines path in URL that is regarded as a "namespace" for this module
# So, /admin means all URLs starting with /admin will be part of the admin module.
# Controller namespace is relative to \\Application\Controller, can be empty.
# Template path is relative to /application/templates, can be empty.
# Secure: Enforces that requests must be made over SSL.
modules:
    site:
        root_path: /
        controller_ns:
        template_path:
        secure: false
    admin:
        root_path: /admin
        controller_ns: Admin
        template_path: /admin
        secure: true

# Database
database:
    username: demo
    password: 123456
    name: framework
    default_object_namespace: \Application\Domain\Entity

# Logging
log:
    path: application/log

# Templating
templating:
    default: page.php
    
# Assets
assets:
    # Merge assets together or not
    merging: on
    
    # Check if sources are newer and make new combined file if necessary
    autorefresh: on
    
    # Minify assets or not
    minify: on
    
    # Shell commands to run the minifier of your choice
    minify_commands:
        styles: "cleancss -o [filename] [filename]"
        scripts: "uglifyjs2 [filename] -o [filename]"
        
    # Default files, must be loaded on every request:
    # Files can be local or remote; remote files must start with //
    # Remote files will be loaded before local files.
    styles:
        - reset.css
        - layout.css
    scripts:
        - //ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js