# Database
database:
    username: demo
    password: 123456
    name: framework
    default_object_namespace: \Application\Domain\Entity

# Logging
log:
    path: application/log

# Templating
templating:
    default: page.php
    
# Assets
assets:
    # Merge assets together or not
    merging: off
    
    # Check if sources are newer and make new combined file if necessary
    autorefresh: on
    
    # Minify assets or not
    minify: on
    
    # Shell commands to run the minifier of your choice
    minify_commands:
        styles: "cleancss -o [filename] [filename]"
        scripts: "uglifyjs2 [filename] -o [filename]"
        
    # Default files, must be loaded on every request:
    # Files can be local or remote; remote files must start with //
    # Remote files will be loaded before local files.
    styles:
        - reset.css
        - layout.css
    scripts:
        - //ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js